###################################################################

# Created by write_sdc on Sun Jun 20 21:18:12 2021

###################################################################
set sdc_version 1.8

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions slow -library slow
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 0.05 [get_ports o_nxt_data]
set_load -pin_load 0.05 [get_ports o_c]
set_load -pin_load 0.05 [get_ports {o_data[127]}]
set_load -pin_load 0.05 [get_ports {o_data[126]}]
set_load -pin_load 0.05 [get_ports {o_data[125]}]
set_load -pin_load 0.05 [get_ports {o_data[124]}]
set_load -pin_load 0.05 [get_ports {o_data[123]}]
set_load -pin_load 0.05 [get_ports {o_data[122]}]
set_load -pin_load 0.05 [get_ports {o_data[121]}]
set_load -pin_load 0.05 [get_ports {o_data[120]}]
set_load -pin_load 0.05 [get_ports {o_data[119]}]
set_load -pin_load 0.05 [get_ports {o_data[118]}]
set_load -pin_load 0.05 [get_ports {o_data[117]}]
set_load -pin_load 0.05 [get_ports {o_data[116]}]
set_load -pin_load 0.05 [get_ports {o_data[115]}]
set_load -pin_load 0.05 [get_ports {o_data[114]}]
set_load -pin_load 0.05 [get_ports {o_data[113]}]
set_load -pin_load 0.05 [get_ports {o_data[112]}]
set_load -pin_load 0.05 [get_ports {o_data[111]}]
set_load -pin_load 0.05 [get_ports {o_data[110]}]
set_load -pin_load 0.05 [get_ports {o_data[109]}]
set_load -pin_load 0.05 [get_ports {o_data[108]}]
set_load -pin_load 0.05 [get_ports {o_data[107]}]
set_load -pin_load 0.05 [get_ports {o_data[106]}]
set_load -pin_load 0.05 [get_ports {o_data[105]}]
set_load -pin_load 0.05 [get_ports {o_data[104]}]
set_load -pin_load 0.05 [get_ports {o_data[103]}]
set_load -pin_load 0.05 [get_ports {o_data[102]}]
set_load -pin_load 0.05 [get_ports {o_data[101]}]
set_load -pin_load 0.05 [get_ports {o_data[100]}]
set_load -pin_load 0.05 [get_ports {o_data[99]}]
set_load -pin_load 0.05 [get_ports {o_data[98]}]
set_load -pin_load 0.05 [get_ports {o_data[97]}]
set_load -pin_load 0.05 [get_ports {o_data[96]}]
set_load -pin_load 0.05 [get_ports {o_data[95]}]
set_load -pin_load 0.05 [get_ports {o_data[94]}]
set_load -pin_load 0.05 [get_ports {o_data[93]}]
set_load -pin_load 0.05 [get_ports {o_data[92]}]
set_load -pin_load 0.05 [get_ports {o_data[91]}]
set_load -pin_load 0.05 [get_ports {o_data[90]}]
set_load -pin_load 0.05 [get_ports {o_data[89]}]
set_load -pin_load 0.05 [get_ports {o_data[88]}]
set_load -pin_load 0.05 [get_ports {o_data[87]}]
set_load -pin_load 0.05 [get_ports {o_data[86]}]
set_load -pin_load 0.05 [get_ports {o_data[85]}]
set_load -pin_load 0.05 [get_ports {o_data[84]}]
set_load -pin_load 0.05 [get_ports {o_data[83]}]
set_load -pin_load 0.05 [get_ports {o_data[82]}]
set_load -pin_load 0.05 [get_ports {o_data[81]}]
set_load -pin_load 0.05 [get_ports {o_data[80]}]
set_load -pin_load 0.05 [get_ports {o_data[79]}]
set_load -pin_load 0.05 [get_ports {o_data[78]}]
set_load -pin_load 0.05 [get_ports {o_data[77]}]
set_load -pin_load 0.05 [get_ports {o_data[76]}]
set_load -pin_load 0.05 [get_ports {o_data[75]}]
set_load -pin_load 0.05 [get_ports {o_data[74]}]
set_load -pin_load 0.05 [get_ports {o_data[73]}]
set_load -pin_load 0.05 [get_ports {o_data[72]}]
set_load -pin_load 0.05 [get_ports {o_data[71]}]
set_load -pin_load 0.05 [get_ports {o_data[70]}]
set_load -pin_load 0.05 [get_ports {o_data[69]}]
set_load -pin_load 0.05 [get_ports {o_data[68]}]
set_load -pin_load 0.05 [get_ports {o_data[67]}]
set_load -pin_load 0.05 [get_ports {o_data[66]}]
set_load -pin_load 0.05 [get_ports {o_data[65]}]
set_load -pin_load 0.05 [get_ports {o_data[64]}]
set_load -pin_load 0.05 [get_ports {o_data[63]}]
set_load -pin_load 0.05 [get_ports {o_data[62]}]
set_load -pin_load 0.05 [get_ports {o_data[61]}]
set_load -pin_load 0.05 [get_ports {o_data[60]}]
set_load -pin_load 0.05 [get_ports {o_data[59]}]
set_load -pin_load 0.05 [get_ports {o_data[58]}]
set_load -pin_load 0.05 [get_ports {o_data[57]}]
set_load -pin_load 0.05 [get_ports {o_data[56]}]
set_load -pin_load 0.05 [get_ports {o_data[55]}]
set_load -pin_load 0.05 [get_ports {o_data[54]}]
set_load -pin_load 0.05 [get_ports {o_data[53]}]
set_load -pin_load 0.05 [get_ports {o_data[52]}]
set_load -pin_load 0.05 [get_ports {o_data[51]}]
set_load -pin_load 0.05 [get_ports {o_data[50]}]
set_load -pin_load 0.05 [get_ports {o_data[49]}]
set_load -pin_load 0.05 [get_ports {o_data[48]}]
set_load -pin_load 0.05 [get_ports {o_data[47]}]
set_load -pin_load 0.05 [get_ports {o_data[46]}]
set_load -pin_load 0.05 [get_ports {o_data[45]}]
set_load -pin_load 0.05 [get_ports {o_data[44]}]
set_load -pin_load 0.05 [get_ports {o_data[43]}]
set_load -pin_load 0.05 [get_ports {o_data[42]}]
set_load -pin_load 0.05 [get_ports {o_data[41]}]
set_load -pin_load 0.05 [get_ports {o_data[40]}]
set_load -pin_load 0.05 [get_ports {o_data[39]}]
set_load -pin_load 0.05 [get_ports {o_data[38]}]
set_load -pin_load 0.05 [get_ports {o_data[37]}]
set_load -pin_load 0.05 [get_ports {o_data[36]}]
set_load -pin_load 0.05 [get_ports {o_data[35]}]
set_load -pin_load 0.05 [get_ports {o_data[34]}]
set_load -pin_load 0.05 [get_ports {o_data[33]}]
set_load -pin_load 0.05 [get_ports {o_data[32]}]
set_load -pin_load 0.05 [get_ports {o_data[31]}]
set_load -pin_load 0.05 [get_ports {o_data[30]}]
set_load -pin_load 0.05 [get_ports {o_data[29]}]
set_load -pin_load 0.05 [get_ports {o_data[28]}]
set_load -pin_load 0.05 [get_ports {o_data[27]}]
set_load -pin_load 0.05 [get_ports {o_data[26]}]
set_load -pin_load 0.05 [get_ports {o_data[25]}]
set_load -pin_load 0.05 [get_ports {o_data[24]}]
set_load -pin_load 0.05 [get_ports {o_data[23]}]
set_load -pin_load 0.05 [get_ports {o_data[22]}]
set_load -pin_load 0.05 [get_ports {o_data[21]}]
set_load -pin_load 0.05 [get_ports {o_data[20]}]
set_load -pin_load 0.05 [get_ports {o_data[19]}]
set_load -pin_load 0.05 [get_ports {o_data[18]}]
set_load -pin_load 0.05 [get_ports {o_data[17]}]
set_load -pin_load 0.05 [get_ports {o_data[16]}]
set_load -pin_load 0.05 [get_ports {o_data[15]}]
set_load -pin_load 0.05 [get_ports {o_data[14]}]
set_load -pin_load 0.05 [get_ports {o_data[13]}]
set_load -pin_load 0.05 [get_ports {o_data[12]}]
set_load -pin_load 0.05 [get_ports {o_data[11]}]
set_load -pin_load 0.05 [get_ports {o_data[10]}]
set_load -pin_load 0.05 [get_ports {o_data[9]}]
set_load -pin_load 0.05 [get_ports {o_data[8]}]
set_load -pin_load 0.05 [get_ports {o_data[7]}]
set_load -pin_load 0.05 [get_ports {o_data[6]}]
set_load -pin_load 0.05 [get_ports {o_data[5]}]
set_load -pin_load 0.05 [get_ports {o_data[4]}]
set_load -pin_load 0.05 [get_ports {o_data[3]}]
set_load -pin_load 0.05 [get_ports {o_data[2]}]
set_load -pin_load 0.05 [get_ports {o_data[1]}]
set_load -pin_load 0.05 [get_ports {o_data[0]}]
set_load -pin_load 0.05 [get_ports o_fin]
set_max_fanout 20 [get_ports {i_data[127]}]
set_max_fanout 20 [get_ports {i_data[126]}]
set_max_fanout 20 [get_ports {i_data[125]}]
set_max_fanout 20 [get_ports {i_data[124]}]
set_max_fanout 20 [get_ports {i_data[123]}]
set_max_fanout 20 [get_ports {i_data[122]}]
set_max_fanout 20 [get_ports {i_data[121]}]
set_max_fanout 20 [get_ports {i_data[120]}]
set_max_fanout 20 [get_ports {i_data[119]}]
set_max_fanout 20 [get_ports {i_data[118]}]
set_max_fanout 20 [get_ports {i_data[117]}]
set_max_fanout 20 [get_ports {i_data[116]}]
set_max_fanout 20 [get_ports {i_data[115]}]
set_max_fanout 20 [get_ports {i_data[114]}]
set_max_fanout 20 [get_ports {i_data[113]}]
set_max_fanout 20 [get_ports {i_data[112]}]
set_max_fanout 20 [get_ports {i_data[111]}]
set_max_fanout 20 [get_ports {i_data[110]}]
set_max_fanout 20 [get_ports {i_data[109]}]
set_max_fanout 20 [get_ports {i_data[108]}]
set_max_fanout 20 [get_ports {i_data[107]}]
set_max_fanout 20 [get_ports {i_data[106]}]
set_max_fanout 20 [get_ports {i_data[105]}]
set_max_fanout 20 [get_ports {i_data[104]}]
set_max_fanout 20 [get_ports {i_data[103]}]
set_max_fanout 20 [get_ports {i_data[102]}]
set_max_fanout 20 [get_ports {i_data[101]}]
set_max_fanout 20 [get_ports {i_data[100]}]
set_max_fanout 20 [get_ports {i_data[99]}]
set_max_fanout 20 [get_ports {i_data[98]}]
set_max_fanout 20 [get_ports {i_data[97]}]
set_max_fanout 20 [get_ports {i_data[96]}]
set_max_fanout 20 [get_ports {i_data[95]}]
set_max_fanout 20 [get_ports {i_data[94]}]
set_max_fanout 20 [get_ports {i_data[93]}]
set_max_fanout 20 [get_ports {i_data[92]}]
set_max_fanout 20 [get_ports {i_data[91]}]
set_max_fanout 20 [get_ports {i_data[90]}]
set_max_fanout 20 [get_ports {i_data[89]}]
set_max_fanout 20 [get_ports {i_data[88]}]
set_max_fanout 20 [get_ports {i_data[87]}]
set_max_fanout 20 [get_ports {i_data[86]}]
set_max_fanout 20 [get_ports {i_data[85]}]
set_max_fanout 20 [get_ports {i_data[84]}]
set_max_fanout 20 [get_ports {i_data[83]}]
set_max_fanout 20 [get_ports {i_data[82]}]
set_max_fanout 20 [get_ports {i_data[81]}]
set_max_fanout 20 [get_ports {i_data[80]}]
set_max_fanout 20 [get_ports {i_data[79]}]
set_max_fanout 20 [get_ports {i_data[78]}]
set_max_fanout 20 [get_ports {i_data[77]}]
set_max_fanout 20 [get_ports {i_data[76]}]
set_max_fanout 20 [get_ports {i_data[75]}]
set_max_fanout 20 [get_ports {i_data[74]}]
set_max_fanout 20 [get_ports {i_data[73]}]
set_max_fanout 20 [get_ports {i_data[72]}]
set_max_fanout 20 [get_ports {i_data[71]}]
set_max_fanout 20 [get_ports {i_data[70]}]
set_max_fanout 20 [get_ports {i_data[69]}]
set_max_fanout 20 [get_ports {i_data[68]}]
set_max_fanout 20 [get_ports {i_data[67]}]
set_max_fanout 20 [get_ports {i_data[66]}]
set_max_fanout 20 [get_ports {i_data[65]}]
set_max_fanout 20 [get_ports {i_data[64]}]
set_max_fanout 20 [get_ports {i_data[63]}]
set_max_fanout 20 [get_ports {i_data[62]}]
set_max_fanout 20 [get_ports {i_data[61]}]
set_max_fanout 20 [get_ports {i_data[60]}]
set_max_fanout 20 [get_ports {i_data[59]}]
set_max_fanout 20 [get_ports {i_data[58]}]
set_max_fanout 20 [get_ports {i_data[57]}]
set_max_fanout 20 [get_ports {i_data[56]}]
set_max_fanout 20 [get_ports {i_data[55]}]
set_max_fanout 20 [get_ports {i_data[54]}]
set_max_fanout 20 [get_ports {i_data[53]}]
set_max_fanout 20 [get_ports {i_data[52]}]
set_max_fanout 20 [get_ports {i_data[51]}]
set_max_fanout 20 [get_ports {i_data[50]}]
set_max_fanout 20 [get_ports {i_data[49]}]
set_max_fanout 20 [get_ports {i_data[48]}]
set_max_fanout 20 [get_ports {i_data[47]}]
set_max_fanout 20 [get_ports {i_data[46]}]
set_max_fanout 20 [get_ports {i_data[45]}]
set_max_fanout 20 [get_ports {i_data[44]}]
set_max_fanout 20 [get_ports {i_data[43]}]
set_max_fanout 20 [get_ports {i_data[42]}]
set_max_fanout 20 [get_ports {i_data[41]}]
set_max_fanout 20 [get_ports {i_data[40]}]
set_max_fanout 20 [get_ports {i_data[39]}]
set_max_fanout 20 [get_ports {i_data[38]}]
set_max_fanout 20 [get_ports {i_data[37]}]
set_max_fanout 20 [get_ports {i_data[36]}]
set_max_fanout 20 [get_ports {i_data[35]}]
set_max_fanout 20 [get_ports {i_data[34]}]
set_max_fanout 20 [get_ports {i_data[33]}]
set_max_fanout 20 [get_ports {i_data[32]}]
set_max_fanout 20 [get_ports {i_data[31]}]
set_max_fanout 20 [get_ports {i_data[30]}]
set_max_fanout 20 [get_ports {i_data[29]}]
set_max_fanout 20 [get_ports {i_data[28]}]
set_max_fanout 20 [get_ports {i_data[27]}]
set_max_fanout 20 [get_ports {i_data[26]}]
set_max_fanout 20 [get_ports {i_data[25]}]
set_max_fanout 20 [get_ports {i_data[24]}]
set_max_fanout 20 [get_ports {i_data[23]}]
set_max_fanout 20 [get_ports {i_data[22]}]
set_max_fanout 20 [get_ports {i_data[21]}]
set_max_fanout 20 [get_ports {i_data[20]}]
set_max_fanout 20 [get_ports {i_data[19]}]
set_max_fanout 20 [get_ports {i_data[18]}]
set_max_fanout 20 [get_ports {i_data[17]}]
set_max_fanout 20 [get_ports {i_data[16]}]
set_max_fanout 20 [get_ports {i_data[15]}]
set_max_fanout 20 [get_ports {i_data[14]}]
set_max_fanout 20 [get_ports {i_data[13]}]
set_max_fanout 20 [get_ports {i_data[12]}]
set_max_fanout 20 [get_ports {i_data[11]}]
set_max_fanout 20 [get_ports {i_data[10]}]
set_max_fanout 20 [get_ports {i_data[9]}]
set_max_fanout 20 [get_ports {i_data[8]}]
set_max_fanout 20 [get_ports {i_data[7]}]
set_max_fanout 20 [get_ports {i_data[6]}]
set_max_fanout 20 [get_ports {i_data[5]}]
set_max_fanout 20 [get_ports {i_data[4]}]
set_max_fanout 20 [get_ports {i_data[3]}]
set_max_fanout 20 [get_ports {i_data[2]}]
set_max_fanout 20 [get_ports {i_data[1]}]
set_max_fanout 20 [get_ports {i_data[0]}]
set_max_fanout 20 [get_ports {i_n[127]}]
set_max_fanout 20 [get_ports {i_n[126]}]
set_max_fanout 20 [get_ports {i_n[125]}]
set_max_fanout 20 [get_ports {i_n[124]}]
set_max_fanout 20 [get_ports {i_n[123]}]
set_max_fanout 20 [get_ports {i_n[122]}]
set_max_fanout 20 [get_ports {i_n[121]}]
set_max_fanout 20 [get_ports {i_n[120]}]
set_max_fanout 20 [get_ports {i_n[119]}]
set_max_fanout 20 [get_ports {i_n[118]}]
set_max_fanout 20 [get_ports {i_n[117]}]
set_max_fanout 20 [get_ports {i_n[116]}]
set_max_fanout 20 [get_ports {i_n[115]}]
set_max_fanout 20 [get_ports {i_n[114]}]
set_max_fanout 20 [get_ports {i_n[113]}]
set_max_fanout 20 [get_ports {i_n[112]}]
set_max_fanout 20 [get_ports {i_n[111]}]
set_max_fanout 20 [get_ports {i_n[110]}]
set_max_fanout 20 [get_ports {i_n[109]}]
set_max_fanout 20 [get_ports {i_n[108]}]
set_max_fanout 20 [get_ports {i_n[107]}]
set_max_fanout 20 [get_ports {i_n[106]}]
set_max_fanout 20 [get_ports {i_n[105]}]
set_max_fanout 20 [get_ports {i_n[104]}]
set_max_fanout 20 [get_ports {i_n[103]}]
set_max_fanout 20 [get_ports {i_n[102]}]
set_max_fanout 20 [get_ports {i_n[101]}]
set_max_fanout 20 [get_ports {i_n[100]}]
set_max_fanout 20 [get_ports {i_n[99]}]
set_max_fanout 20 [get_ports {i_n[98]}]
set_max_fanout 20 [get_ports {i_n[97]}]
set_max_fanout 20 [get_ports {i_n[96]}]
set_max_fanout 20 [get_ports {i_n[95]}]
set_max_fanout 20 [get_ports {i_n[94]}]
set_max_fanout 20 [get_ports {i_n[93]}]
set_max_fanout 20 [get_ports {i_n[92]}]
set_max_fanout 20 [get_ports {i_n[91]}]
set_max_fanout 20 [get_ports {i_n[90]}]
set_max_fanout 20 [get_ports {i_n[89]}]
set_max_fanout 20 [get_ports {i_n[88]}]
set_max_fanout 20 [get_ports {i_n[87]}]
set_max_fanout 20 [get_ports {i_n[86]}]
set_max_fanout 20 [get_ports {i_n[85]}]
set_max_fanout 20 [get_ports {i_n[84]}]
set_max_fanout 20 [get_ports {i_n[83]}]
set_max_fanout 20 [get_ports {i_n[82]}]
set_max_fanout 20 [get_ports {i_n[81]}]
set_max_fanout 20 [get_ports {i_n[80]}]
set_max_fanout 20 [get_ports {i_n[79]}]
set_max_fanout 20 [get_ports {i_n[78]}]
set_max_fanout 20 [get_ports {i_n[77]}]
set_max_fanout 20 [get_ports {i_n[76]}]
set_max_fanout 20 [get_ports {i_n[75]}]
set_max_fanout 20 [get_ports {i_n[74]}]
set_max_fanout 20 [get_ports {i_n[73]}]
set_max_fanout 20 [get_ports {i_n[72]}]
set_max_fanout 20 [get_ports {i_n[71]}]
set_max_fanout 20 [get_ports {i_n[70]}]
set_max_fanout 20 [get_ports {i_n[69]}]
set_max_fanout 20 [get_ports {i_n[68]}]
set_max_fanout 20 [get_ports {i_n[67]}]
set_max_fanout 20 [get_ports {i_n[66]}]
set_max_fanout 20 [get_ports {i_n[65]}]
set_max_fanout 20 [get_ports {i_n[64]}]
set_max_fanout 20 [get_ports {i_n[63]}]
set_max_fanout 20 [get_ports {i_n[62]}]
set_max_fanout 20 [get_ports {i_n[61]}]
set_max_fanout 20 [get_ports {i_n[60]}]
set_max_fanout 20 [get_ports {i_n[59]}]
set_max_fanout 20 [get_ports {i_n[58]}]
set_max_fanout 20 [get_ports {i_n[57]}]
set_max_fanout 20 [get_ports {i_n[56]}]
set_max_fanout 20 [get_ports {i_n[55]}]
set_max_fanout 20 [get_ports {i_n[54]}]
set_max_fanout 20 [get_ports {i_n[53]}]
set_max_fanout 20 [get_ports {i_n[52]}]
set_max_fanout 20 [get_ports {i_n[51]}]
set_max_fanout 20 [get_ports {i_n[50]}]
set_max_fanout 20 [get_ports {i_n[49]}]
set_max_fanout 20 [get_ports {i_n[48]}]
set_max_fanout 20 [get_ports {i_n[47]}]
set_max_fanout 20 [get_ports {i_n[46]}]
set_max_fanout 20 [get_ports {i_n[45]}]
set_max_fanout 20 [get_ports {i_n[44]}]
set_max_fanout 20 [get_ports {i_n[43]}]
set_max_fanout 20 [get_ports {i_n[42]}]
set_max_fanout 20 [get_ports {i_n[41]}]
set_max_fanout 20 [get_ports {i_n[40]}]
set_max_fanout 20 [get_ports {i_n[39]}]
set_max_fanout 20 [get_ports {i_n[38]}]
set_max_fanout 20 [get_ports {i_n[37]}]
set_max_fanout 20 [get_ports {i_n[36]}]
set_max_fanout 20 [get_ports {i_n[35]}]
set_max_fanout 20 [get_ports {i_n[34]}]
set_max_fanout 20 [get_ports {i_n[33]}]
set_max_fanout 20 [get_ports {i_n[32]}]
set_max_fanout 20 [get_ports {i_n[31]}]
set_max_fanout 20 [get_ports {i_n[30]}]
set_max_fanout 20 [get_ports {i_n[29]}]
set_max_fanout 20 [get_ports {i_n[28]}]
set_max_fanout 20 [get_ports {i_n[27]}]
set_max_fanout 20 [get_ports {i_n[26]}]
set_max_fanout 20 [get_ports {i_n[25]}]
set_max_fanout 20 [get_ports {i_n[24]}]
set_max_fanout 20 [get_ports {i_n[23]}]
set_max_fanout 20 [get_ports {i_n[22]}]
set_max_fanout 20 [get_ports {i_n[21]}]
set_max_fanout 20 [get_ports {i_n[20]}]
set_max_fanout 20 [get_ports {i_n[19]}]
set_max_fanout 20 [get_ports {i_n[18]}]
set_max_fanout 20 [get_ports {i_n[17]}]
set_max_fanout 20 [get_ports {i_n[16]}]
set_max_fanout 20 [get_ports {i_n[15]}]
set_max_fanout 20 [get_ports {i_n[14]}]
set_max_fanout 20 [get_ports {i_n[13]}]
set_max_fanout 20 [get_ports {i_n[12]}]
set_max_fanout 20 [get_ports {i_n[11]}]
set_max_fanout 20 [get_ports {i_n[10]}]
set_max_fanout 20 [get_ports {i_n[9]}]
set_max_fanout 20 [get_ports {i_n[8]}]
set_max_fanout 20 [get_ports {i_n[7]}]
set_max_fanout 20 [get_ports {i_n[6]}]
set_max_fanout 20 [get_ports {i_n[5]}]
set_max_fanout 20 [get_ports {i_n[4]}]
set_max_fanout 20 [get_ports {i_n[3]}]
set_max_fanout 20 [get_ports {i_n[2]}]
set_max_fanout 20 [get_ports {i_n[1]}]
set_max_fanout 20 [get_ports {i_n[0]}]
set_max_fanout 20 [get_ports {i_k[127]}]
set_max_fanout 20 [get_ports {i_k[126]}]
set_max_fanout 20 [get_ports {i_k[125]}]
set_max_fanout 20 [get_ports {i_k[124]}]
set_max_fanout 20 [get_ports {i_k[123]}]
set_max_fanout 20 [get_ports {i_k[122]}]
set_max_fanout 20 [get_ports {i_k[121]}]
set_max_fanout 20 [get_ports {i_k[120]}]
set_max_fanout 20 [get_ports {i_k[119]}]
set_max_fanout 20 [get_ports {i_k[118]}]
set_max_fanout 20 [get_ports {i_k[117]}]
set_max_fanout 20 [get_ports {i_k[116]}]
set_max_fanout 20 [get_ports {i_k[115]}]
set_max_fanout 20 [get_ports {i_k[114]}]
set_max_fanout 20 [get_ports {i_k[113]}]
set_max_fanout 20 [get_ports {i_k[112]}]
set_max_fanout 20 [get_ports {i_k[111]}]
set_max_fanout 20 [get_ports {i_k[110]}]
set_max_fanout 20 [get_ports {i_k[109]}]
set_max_fanout 20 [get_ports {i_k[108]}]
set_max_fanout 20 [get_ports {i_k[107]}]
set_max_fanout 20 [get_ports {i_k[106]}]
set_max_fanout 20 [get_ports {i_k[105]}]
set_max_fanout 20 [get_ports {i_k[104]}]
set_max_fanout 20 [get_ports {i_k[103]}]
set_max_fanout 20 [get_ports {i_k[102]}]
set_max_fanout 20 [get_ports {i_k[101]}]
set_max_fanout 20 [get_ports {i_k[100]}]
set_max_fanout 20 [get_ports {i_k[99]}]
set_max_fanout 20 [get_ports {i_k[98]}]
set_max_fanout 20 [get_ports {i_k[97]}]
set_max_fanout 20 [get_ports {i_k[96]}]
set_max_fanout 20 [get_ports {i_k[95]}]
set_max_fanout 20 [get_ports {i_k[94]}]
set_max_fanout 20 [get_ports {i_k[93]}]
set_max_fanout 20 [get_ports {i_k[92]}]
set_max_fanout 20 [get_ports {i_k[91]}]
set_max_fanout 20 [get_ports {i_k[90]}]
set_max_fanout 20 [get_ports {i_k[89]}]
set_max_fanout 20 [get_ports {i_k[88]}]
set_max_fanout 20 [get_ports {i_k[87]}]
set_max_fanout 20 [get_ports {i_k[86]}]
set_max_fanout 20 [get_ports {i_k[85]}]
set_max_fanout 20 [get_ports {i_k[84]}]
set_max_fanout 20 [get_ports {i_k[83]}]
set_max_fanout 20 [get_ports {i_k[82]}]
set_max_fanout 20 [get_ports {i_k[81]}]
set_max_fanout 20 [get_ports {i_k[80]}]
set_max_fanout 20 [get_ports {i_k[79]}]
set_max_fanout 20 [get_ports {i_k[78]}]
set_max_fanout 20 [get_ports {i_k[77]}]
set_max_fanout 20 [get_ports {i_k[76]}]
set_max_fanout 20 [get_ports {i_k[75]}]
set_max_fanout 20 [get_ports {i_k[74]}]
set_max_fanout 20 [get_ports {i_k[73]}]
set_max_fanout 20 [get_ports {i_k[72]}]
set_max_fanout 20 [get_ports {i_k[71]}]
set_max_fanout 20 [get_ports {i_k[70]}]
set_max_fanout 20 [get_ports {i_k[69]}]
set_max_fanout 20 [get_ports {i_k[68]}]
set_max_fanout 20 [get_ports {i_k[67]}]
set_max_fanout 20 [get_ports {i_k[66]}]
set_max_fanout 20 [get_ports {i_k[65]}]
set_max_fanout 20 [get_ports {i_k[64]}]
set_max_fanout 20 [get_ports {i_k[63]}]
set_max_fanout 20 [get_ports {i_k[62]}]
set_max_fanout 20 [get_ports {i_k[61]}]
set_max_fanout 20 [get_ports {i_k[60]}]
set_max_fanout 20 [get_ports {i_k[59]}]
set_max_fanout 20 [get_ports {i_k[58]}]
set_max_fanout 20 [get_ports {i_k[57]}]
set_max_fanout 20 [get_ports {i_k[56]}]
set_max_fanout 20 [get_ports {i_k[55]}]
set_max_fanout 20 [get_ports {i_k[54]}]
set_max_fanout 20 [get_ports {i_k[53]}]
set_max_fanout 20 [get_ports {i_k[52]}]
set_max_fanout 20 [get_ports {i_k[51]}]
set_max_fanout 20 [get_ports {i_k[50]}]
set_max_fanout 20 [get_ports {i_k[49]}]
set_max_fanout 20 [get_ports {i_k[48]}]
set_max_fanout 20 [get_ports {i_k[47]}]
set_max_fanout 20 [get_ports {i_k[46]}]
set_max_fanout 20 [get_ports {i_k[45]}]
set_max_fanout 20 [get_ports {i_k[44]}]
set_max_fanout 20 [get_ports {i_k[43]}]
set_max_fanout 20 [get_ports {i_k[42]}]
set_max_fanout 20 [get_ports {i_k[41]}]
set_max_fanout 20 [get_ports {i_k[40]}]
set_max_fanout 20 [get_ports {i_k[39]}]
set_max_fanout 20 [get_ports {i_k[38]}]
set_max_fanout 20 [get_ports {i_k[37]}]
set_max_fanout 20 [get_ports {i_k[36]}]
set_max_fanout 20 [get_ports {i_k[35]}]
set_max_fanout 20 [get_ports {i_k[34]}]
set_max_fanout 20 [get_ports {i_k[33]}]
set_max_fanout 20 [get_ports {i_k[32]}]
set_max_fanout 20 [get_ports {i_k[31]}]
set_max_fanout 20 [get_ports {i_k[30]}]
set_max_fanout 20 [get_ports {i_k[29]}]
set_max_fanout 20 [get_ports {i_k[28]}]
set_max_fanout 20 [get_ports {i_k[27]}]
set_max_fanout 20 [get_ports {i_k[26]}]
set_max_fanout 20 [get_ports {i_k[25]}]
set_max_fanout 20 [get_ports {i_k[24]}]
set_max_fanout 20 [get_ports {i_k[23]}]
set_max_fanout 20 [get_ports {i_k[22]}]
set_max_fanout 20 [get_ports {i_k[21]}]
set_max_fanout 20 [get_ports {i_k[20]}]
set_max_fanout 20 [get_ports {i_k[19]}]
set_max_fanout 20 [get_ports {i_k[18]}]
set_max_fanout 20 [get_ports {i_k[17]}]
set_max_fanout 20 [get_ports {i_k[16]}]
set_max_fanout 20 [get_ports {i_k[15]}]
set_max_fanout 20 [get_ports {i_k[14]}]
set_max_fanout 20 [get_ports {i_k[13]}]
set_max_fanout 20 [get_ports {i_k[12]}]
set_max_fanout 20 [get_ports {i_k[11]}]
set_max_fanout 20 [get_ports {i_k[10]}]
set_max_fanout 20 [get_ports {i_k[9]}]
set_max_fanout 20 [get_ports {i_k[8]}]
set_max_fanout 20 [get_ports {i_k[7]}]
set_max_fanout 20 [get_ports {i_k[6]}]
set_max_fanout 20 [get_ports {i_k[5]}]
set_max_fanout 20 [get_ports {i_k[4]}]
set_max_fanout 20 [get_ports {i_k[3]}]
set_max_fanout 20 [get_ports {i_k[2]}]
set_max_fanout 20 [get_ports {i_k[1]}]
set_max_fanout 20 [get_ports {i_k[0]}]
set_max_fanout 20 [get_ports clk]
set_max_fanout 20 [get_ports i_rst]
set_max_fanout 20 [get_ports i_start]
set_max_fanout 20 [get_ports {i_a_len[15]}]
set_max_fanout 20 [get_ports {i_a_len[14]}]
set_max_fanout 20 [get_ports {i_a_len[13]}]
set_max_fanout 20 [get_ports {i_a_len[12]}]
set_max_fanout 20 [get_ports {i_a_len[11]}]
set_max_fanout 20 [get_ports {i_a_len[10]}]
set_max_fanout 20 [get_ports {i_a_len[9]}]
set_max_fanout 20 [get_ports {i_a_len[8]}]
set_max_fanout 20 [get_ports {i_a_len[7]}]
set_max_fanout 20 [get_ports {i_a_len[6]}]
set_max_fanout 20 [get_ports {i_a_len[5]}]
set_max_fanout 20 [get_ports {i_a_len[4]}]
set_max_fanout 20 [get_ports {i_a_len[3]}]
set_max_fanout 20 [get_ports {i_a_len[2]}]
set_max_fanout 20 [get_ports {i_a_len[1]}]
set_max_fanout 20 [get_ports {i_a_len[0]}]
set_max_fanout 20 [get_ports {i_m_len[15]}]
set_max_fanout 20 [get_ports {i_m_len[14]}]
set_max_fanout 20 [get_ports {i_m_len[13]}]
set_max_fanout 20 [get_ports {i_m_len[12]}]
set_max_fanout 20 [get_ports {i_m_len[11]}]
set_max_fanout 20 [get_ports {i_m_len[10]}]
set_max_fanout 20 [get_ports {i_m_len[9]}]
set_max_fanout 20 [get_ports {i_m_len[8]}]
set_max_fanout 20 [get_ports {i_m_len[7]}]
set_max_fanout 20 [get_ports {i_m_len[6]}]
set_max_fanout 20 [get_ports {i_m_len[5]}]
set_max_fanout 20 [get_ports {i_m_len[4]}]
set_max_fanout 20 [get_ports {i_m_len[3]}]
set_max_fanout 20 [get_ports {i_m_len[2]}]
set_max_fanout 20 [get_ports {i_m_len[1]}]
set_max_fanout 20 [get_ports {i_m_len[0]}]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -period 3  -waveform {0 1.5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  0.5  [get_ports {i_data[127]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[126]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[125]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[124]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[123]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[122]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[121]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[120]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[119]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[118]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[117]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[116]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[115]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[114]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[113]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[112]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[111]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[110]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[109]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[108]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[107]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[106]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[105]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[104]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[103]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[102]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[101]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[100]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[99]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[98]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[97]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[96]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[95]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[94]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[93]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[92]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[91]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[90]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[89]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[88]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[87]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[86]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[85]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[84]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[83]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[82]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[81]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[80]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[79]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[78]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[77]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[76]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[75]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[74]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[73]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[72]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[71]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[70]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[69]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[68]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[67]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[66]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[65]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[64]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[63]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[62]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[61]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[60]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[59]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[58]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[57]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[56]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[55]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[54]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[53]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[52]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[51]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[50]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[49]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[48]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[47]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[46]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[45]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[44]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[43]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[42]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[41]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[40]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[39]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[38]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[37]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[36]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[35]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[34]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[33]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[32]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[31]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[30]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[29]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[28]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[27]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[26]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[25]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[24]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[23]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[22]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[21]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[20]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[19]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[18]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[17]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[16]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[15]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[14]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[13]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[12]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[11]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[10]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[9]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[8]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[7]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[6]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[5]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[4]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[3]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[2]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[1]}]
set_input_delay -clock clk  0.5  [get_ports {i_data[0]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[127]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[126]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[125]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[124]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[123]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[122]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[121]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[120]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[119]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[118]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[117]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[116]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[115]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[114]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[113]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[112]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[111]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[110]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[109]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[108]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[107]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[106]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[105]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[104]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[103]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[102]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[101]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[100]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[99]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[98]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[97]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[96]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[95]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[94]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[93]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[92]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[91]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[90]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[89]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[88]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[87]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[86]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[85]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[84]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[83]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[82]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[81]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[80]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[79]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[78]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[77]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[76]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[75]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[74]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[73]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[72]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[71]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[70]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[69]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[68]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[67]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[66]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[65]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[64]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[63]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[62]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[61]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[60]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[59]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[58]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[57]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[56]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[55]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[54]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[53]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[52]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[51]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[50]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[49]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[48]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[47]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[46]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[45]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[44]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[43]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[42]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[41]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[40]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[39]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[38]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[37]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[36]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[35]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[34]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[33]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[32]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[31]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[30]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[29]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[28]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[27]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[26]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[25]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[24]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[23]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[22]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[21]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[20]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[19]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[18]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[17]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[16]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[15]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[14]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[13]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[12]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[11]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[10]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[9]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[8]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[7]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[6]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[5]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[4]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[3]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[2]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[1]}]
set_input_delay -clock clk  0.5  [get_ports {i_n[0]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[127]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[126]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[125]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[124]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[123]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[122]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[121]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[120]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[119]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[118]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[117]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[116]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[115]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[114]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[113]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[112]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[111]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[110]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[109]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[108]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[107]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[106]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[105]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[104]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[103]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[102]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[101]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[100]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[99]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[98]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[97]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[96]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[95]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[94]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[93]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[92]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[91]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[90]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[89]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[88]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[87]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[86]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[85]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[84]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[83]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[82]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[81]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[80]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[79]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[78]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[77]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[76]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[75]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[74]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[73]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[72]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[71]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[70]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[69]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[68]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[67]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[66]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[65]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[64]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[63]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[62]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[61]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[60]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[59]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[58]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[57]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[56]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[55]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[54]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[53]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[52]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[51]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[50]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[49]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[48]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[47]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[46]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[45]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[44]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[43]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[42]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[41]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[40]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[39]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[38]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[37]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[36]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[35]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[34]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[33]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[32]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[31]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[30]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[29]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[28]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[27]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[26]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[25]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[24]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[23]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[22]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[21]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[20]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[19]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[18]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[17]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[16]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[15]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[14]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[13]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[12]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[11]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[10]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[9]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[8]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[7]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[6]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[5]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[4]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[3]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[2]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[1]}]
set_input_delay -clock clk  0.5  [get_ports {i_k[0]}]
set_input_delay -clock clk  0.5  [get_ports i_rst]
set_input_delay -clock clk  0.5  [get_ports i_start]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[15]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[14]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[13]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[12]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[11]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[10]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[9]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[8]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[7]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[6]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[5]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[4]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[3]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[2]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[1]}]
set_input_delay -clock clk  0.5  [get_ports {i_a_len[0]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[15]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[14]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[13]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[12]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[11]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[10]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[9]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[8]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[7]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[6]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[5]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[4]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[3]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[2]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[1]}]
set_input_delay -clock clk  0.5  [get_ports {i_m_len[0]}]
set_output_delay -clock clk  0.5  [get_ports o_nxt_data]
set_output_delay -clock clk  0.5  [get_ports o_c]
set_output_delay -clock clk  0.5  [get_ports {o_data[127]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[126]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[125]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[124]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[123]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[122]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[121]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[120]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[119]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[118]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[117]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[116]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[115]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[114]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[113]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[112]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[111]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[110]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[109]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[108]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[107]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[106]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[105]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[104]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[103]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[102]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[101]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[100]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[99]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[98]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[97]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[96]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[95]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[94]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[93]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[92]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[91]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[90]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[89]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[88]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[87]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[86]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[85]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[84]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[83]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[82]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[81]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[80]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[79]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[78]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[77]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[76]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[75]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[74]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[73]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[72]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[71]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[70]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[69]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[68]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[67]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[66]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[65]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[64]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[63]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[62]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[61]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[60]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[59]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[58]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[57]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[56]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[55]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[54]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[53]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[52]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[51]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[50]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[49]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[48]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[47]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[46]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[45]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[44]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[43]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[42]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[41]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[40]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[39]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[38]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[37]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[36]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[35]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[34]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[33]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[32]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_data[0]}]
set_output_delay -clock clk  0.5  [get_ports o_fin]
